<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/Boolean_Indexing_With_More_than_One_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np
import matplotlib.pyplot as plt

In [55]:
#We make a 3D array  of shape (4,3,2)
plane0 = np.reshape(np.arange(12),(4,3))
plane0.shape

(4, 3)

In [56]:
#Create an array of numbers from 100 to 111 
plane1 = np.reshape(np.arange(100,112),(4,3))
plane1.shape

(4, 3)

In [57]:
new_array = np.reshape(np.arange(20), (10,2))
new_array.shape

(10, 2)

In [58]:
#Create a 3d array with 4 rows ,  3 columns and 2 planes 
array_3d = np.zeros((4,3,2)) #Create an empty 3D array

In [59]:
plane0 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
array_3d[:,:,0] = plane0

In [61]:
array_3d #We fill the first plane with the elements of plane0 

array([[[ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.]],

       [[ 3.,  0.],
        [ 4.,  0.],
        [ 5.,  0.]],

       [[ 6.,  0.],
        [ 7.,  0.],
        [ 8.,  0.]],

       [[ 9.,  0.],
        [10.,  0.],
        [11.,  0.]]])

In [62]:
#We set the second plane to be equal to plane1 
array_3d[:,:,1] = plane1
array_3d

array([[[  0., 100.],
        [  1., 101.],
        [  2., 102.]],

       [[  3., 103.],
        [  4., 104.],
        [  5., 105.]],

       [[  6., 106.],
        [  7., 107.],
        [  8., 108.]],

       [[  9., 109.],
        [ 10., 110.],
        [ 11., 111.]]])

In [63]:
bool_array = np.array([1,3,4,2])
bool_array>2


array([False,  True,  True, False])

In [64]:
#array_3d[bool_array]

In [65]:
array_3d = np.zeros((4,3,2))

In [66]:
array_3d[:,:,0] = plane0

In [67]:
array_3d[:,:,1] = plane1
array_3d

array([[[  0., 100.],
        [  1., 101.],
        [  2., 102.]],

       [[  3., 103.],
        [  4., 104.],
        [  5., 105.]],

       [[  6., 106.],
        [  7., 107.],
        [  8., 108.]],

       [[  9., 109.],
        [ 10., 110.],
        [ 11., 111.]]])

In [68]:
#array_3d[bool_array]
bool_array

array([1, 3, 4, 2])

In [69]:
bool_array = bool_array<2
bool_array 
array_3d[bool_array]

array([[[  0., 100.],
        [  1., 101.],
        [  2., 102.]]])

In [70]:
bool_2d = np.array([[False, True, False],
                    [True, False, True],
                    [True, False, False],
                    [False, False, True],
                   ])
bool_2d

array([[False,  True, False],
       [ True, False,  True],
       [ True, False, False],
       [False, False,  True]])

In [72]:
array_3d[bool_2d].shape

(5, 2)

In [74]:
bool_3d = np.zeros((4,3,2),dtype=bool)
bool_3d

array([[[False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False]]])

In [80]:
#We fill in the first plane with the original 2D array 
bool_3d = bool_2d
bool_3d.dtype 

dtype('bool')

In [82]:
#We use the bool_3d to index the array_3d
array_3d[bool_3d]

array([[  1., 101.],
       [  3., 103.],
       [  5., 105.],
       [  6., 106.],
       [ 11., 111.]])

In [84]:
bool_1d_dim3 = np.array([False,True])

array_3d[:,:, bool_1d_dim3]

array([[[100.],
        [101.],
        [102.]],

       [[103.],
        [104.],
        [105.]],

       [[106.],
        [107.],
        [108.]],

       [[109.],
        [110.],
        [111.]]])