<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/Loss_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
!pip install -Uqq fastbook

In [101]:
import fastbook
fastbook.setup_book()
from fastbook import *


In [102]:
from fastai.vision.all import *

In [103]:
path = untar_data(URLs.MNIST_SAMPLE)










In [104]:
path.ls()

(#3) [Path('/root/.fastai/data/mnist_sample/valid'),Path('/root/.fastai/data/mnist_sample/train'),Path('/root/.fastai/data/mnist_sample/labels.csv')]

In [105]:
threes = (path/'train'/'3').ls().sorted()

In [106]:
Image_threes= Image.open(threes[0])

In [107]:
Image_threes

In [108]:
sevens = (path/'train'/'7').ls()

In [109]:
Image_sevens = Image.open(sevens[0])
Image_sevens

In [ ]:
array(Image_sevens)[0:28, 0:28]

In [111]:
tensor(Image_sevens)[4:10][4:10]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,  18, 123, 174, 174, 174, 175, 100, 229, 253,  58,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  86, 253,  58,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=torch.uint8)

In [112]:
image_three_tensor = tensor(Image_threes)[4:15][4:22]

In [113]:
image_three_tensor

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 207, 254, 210, 254, 254, 254,  34,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  84, 206, 254, 254, 254, 254,  41,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 209, 254, 254, 254, 171,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  91, 137, 253, 254, 254, 254, 112,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  40, 214, 250, 254, 254, 254, 254, 254,  34,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  81, 247, 254, 254, 254, 254, 254, 254, 146,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 110, 246, 254, 254, 254, 254, 254, 1

In [114]:
df = pd.DataFrame(image_three_tensor)

In [115]:
df.style.set_properties(**{'font - size': '6pt'}).background_gradient('Greys')

In [116]:
Image_sevens_tensor = tensor(Image_sevens)[4:15][4:22]

In [117]:
df = pd.DataFrame(Image_sevens_tensor)

In [118]:
df.style.set_properties(**{'font - size': '6pt'}).background_gradient('Greys')

In [119]:
threes_tensor  = [tensor(Image.open(o)) for o in threes]

In [ ]:
threes_tensor

In [121]:
sevens_tensor = [tensor(Image.open(o)) for o in sevens]

In [ ]:
sevens_tensor[0]

In [123]:
!pip install torchvision

In [124]:
import torch
import torchvision

In [125]:
sevens_stack = torch.stack(sevens_tensor).float() /255

In [126]:
threes_stack = torch.stack(threes_tensor).float() /255

In [149]:
sevens_stack.shape




torch.Size([6265, 28, 28])

In [148]:
len(sevens_stack.shape)

3

In [147]:
valid_3_tens = torch.stack([tensor(Image.open(o)) for o in(threes)])

In [130]:
valid_7_tens = torch.stack([tensor(Image.open(o)) for o in(sevens)])
 

In [146]:
valid_3_tens = valid_3_tens.float() / 255

In [150]:
#Changing the shape of our tensor without altering the contents
train_x = torch.cat([sevens_stack, threes_stack]).view(-1,28 * 28)

In [151]:
train_x.shape

torch.Size([12396, 784])

In [134]:
#labeled training set 
train_y = tensor([1] * len(threes) + [0] * len(sevens)).unsqueeze(1)

In [152]:
train_y.shape

torch.Size([12396, 1])

In [135]:
dset = list(zip(train_x, train_y))

In [ ]:
dset[0]

In [155]:
#Here we change the contents of our tensor without altering the contents
valid_x  = torch.cat([valid_3_tens, valid_7_tens]).view(-1, 28 * 28)

In [156]:
valid_y = tensor([1] * len(valid_3_tens)  +  [0] * len(valid_7_tens)) 

In [157]:
valid_dset= list(zip(valid_x, valid_y))

In [158]:
#Here we create a function to randomly initialize the weights 
def init_params(size, std=1.0):
  return (torch.randn(size)*std).requires_grad_() 

In [162]:
weights = init_params((28 * 28,1))

In [163]:
bias = init_params(1)

In [164]:
#prediction for one image

prediction = (train_x[0]*weights.T).sum() + bias

In [165]:
prediction

tensor([4.2878], grad_fn=<AddBackward0>)

In [166]:
def linear1(xb): return xb@weights + bias

In [167]:
preds = linear1(train_x)

In [168]:
preds

tensor([[ 4.2878],
        [ 1.4911],
        [-1.8253],
        ...,
        [10.1987],
        [17.3062],
        [11.0816]], grad_fn=<AddBackward0>)

In [169]:
corrects = (preds>0.0) == train_y

In [170]:
corrects

tensor([[ True],
        [ True],
        [False],
        ...,
        [False],
        [False],
        [False]])

In [172]:
corrects.float().mean().item()

0.47652468085289

In [ ]:
weights[0] *= 1.0001

In [ ]:
#Loss function calculates how fast our model is from the desired value or target value, it does this by taking the difference between the actual value minus the predicted value



In [ ]:
#The equation y = wx + b represents our prediction y is the predicted value w is the weights of our model which is a matrix and x is the input values  while b is a bias
#When we slightly alter the weights w we expect the predicted value y to either rise or fall depending on the direction of the alteration


In [178]:
trgts = tensor([1,0,1])
prctd = tensor([0.9, 0.4, 0.2]) 

In [182]:
#define a function called mnist_loss that takes in two parameters predictions and targets 
#then returns an expression that has a pytorch method torch.where, we pass in the target and equate it to 1 then get the 
#difference of the target and the predictions then calculate the mean
def mnist_loss(predictions, targets):
  return torch.where(targets==1, 1 - predictions, predictions).mean()



In [183]:
torch.where(trgts == 1, 1 - prctd, prctd)

tensor([0.1000, 0.4000, 0.8000])

In [184]:
mnist_loss(prctd, trgts)

tensor(0.4333)