<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/Loss_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -Uqq fastbook

     |████████████████████████████████| 720 kB 8.4 MB/s 
     |████████████████████████████████| 46 kB 2.2 MB/s 
     |████████████████████████████████| 189 kB 40.6 MB/s 
     |████████████████████████████████| 1.2 MB 28.6 MB/s 
     |████████████████████████████████| 56 kB 2.3 MB/s 
     |████████████████████████████████| 51 kB 283 kB/s 


In [2]:
import fastbook
fastbook.setup_book()
from fastbook import *


Mounted at /content/gdrive


In [3]:
from fastai.vision.all import *

In [15]:
path = untar_data(URLs.MNIST_SAMPLE)

In [16]:
path.ls()

(#3) [Path('/root/.fastai/data/mnist_sample/labels.csv'),Path('/root/.fastai/data/mnist_sample/train'),Path('/root/.fastai/data/mnist_sample/valid')]

In [17]:
(path/'train').ls()

(#2) [Path('/root/.fastai/data/mnist_sample/train/7'),Path('/root/.fastai/data/mnist_sample/train/3')]

In [18]:
(path/'train'/'3').ls()

(#6131) [Path('/root/.fastai/data/mnist_sample/train/3/18453.png'),Path('/root/.fastai/data/mnist_sample/train/3/2774.png'),Path('/root/.fastai/data/mnist_sample/train/3/13026.png'),Path('/root/.fastai/data/mnist_sample/train/3/50201.png'),Path('/root/.fastai/data/mnist_sample/train/3/45273.png'),Path('/root/.fastai/data/mnist_sample/train/3/2128.png'),Path('/root/.fastai/data/mnist_sample/train/3/50481.png'),Path('/root/.fastai/data/mnist_sample/train/3/50403.png'),Path('/root/.fastai/data/mnist_sample/train/3/28380.png'),Path('/root/.fastai/data/mnist_sample/train/3/28796.png')...]

In [19]:
(path/'train'/'7').ls()

(#6265) [Path('/root/.fastai/data/mnist_sample/train/7/53614.png'),Path('/root/.fastai/data/mnist_sample/train/7/21662.png'),Path('/root/.fastai/data/mnist_sample/train/7/39659.png'),Path('/root/.fastai/data/mnist_sample/train/7/45374.png'),Path('/root/.fastai/data/mnist_sample/train/7/26894.png'),Path('/root/.fastai/data/mnist_sample/train/7/21624.png'),Path('/root/.fastai/data/mnist_sample/train/7/6167.png'),Path('/root/.fastai/data/mnist_sample/train/7/8214.png'),Path('/root/.fastai/data/mnist_sample/train/7/24181.png'),Path('/root/.fastai/data/mnist_sample/train/7/53666.png')...]

In [24]:
threes = (path/'train'/'3').ls().sorted()
#This is how we assign images labeled 3 to a variable so that we can easily access it

In [26]:
sevens = (path/'train'/'7').ls().sorted()
#This here assign the path to our 7 images to a variable that we will use to access

In [28]:
image_three = threes[0]

In [29]:
image_three

Path('/root/.fastai/data/mnist_sample/train/3/10.png')

In [30]:
Image.open(threes[0])

In [32]:
open_threes = Image.open(image_three)

In [33]:
open_threes

In [34]:
image_seven = Image.open(sevens[0])

In [35]:
image_seven

In [ ]:
array(image_seven)[0:28,0:28]
#Here we take the image of 7 we stored in the variable image_seven earlier and then pass it into an array and size it up to 28 by 28 rows and columns


In [42]:
#Here we can also pass it into a tensor
tensor(image_seven)[4:10][4:10]

tensor([[  0,   0,   0,  21, 161, 250, 250, 252, 250, 250, 250, 252, 250, 250, 250, 252, 250, 250, 250, 252, 250, 100,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,  51, 250, 250, 250, 252, 189, 190, 250, 252, 250, 250, 250, 252, 250, 250, 250, 252, 189,  40,   0,   0,   0,   0,   0,   0]], dtype=torch.uint8)

In [43]:
image_three = Image.open(threes[0])

In [44]:
image_three

In [48]:
#Here we turn our 3 image stored in image_three into a tensor
image_three_tensor = tensor(Image.open(threes[0]))

In [53]:
#We then parse the tensor into a data frame 
df = pd.DataFrame(image_three_tensor[4:15,4:22])

In [55]:
df.style.set_properties(**{'font - size':'6pt'}).background_gradient('Greys')

In [56]:
#Here we turn image seven into a tensor 
image_seven_tensor = tensor(Image.open(sevens[0]))

In [58]:
#Here we pass the image tensor seven into a data Frame 
df_seven = pd.DataFrame(image_seven_tensor[4:10,4:22])  


In [62]:
#Here we attempt to color code the pixel values based on the intensity and range
df_seven.style.set_properties(**{'font - size' : '6pt'}).background_gradient('Greys')

In [68]:
#Here we pass all the training images of 7 into a tensor 
sevens_tensor = [tensor(Image.open(o)) for o in sevens]

In [69]:
#Here we do the same for threes
threes_tensor = [tensor(Image.open(o))for o in sevens]

In [70]:
sevens_tensor[0]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  

In [72]:
!pip install torchvision

In [73]:
import torch 
import torchvision

In [77]:
sevens_stack = torch.stack(sevens_tensor).float()/255

In [75]:
three_stack= torch.stack(threes_tensor).float()/ 255

In [80]:
train_x =  torch.cat([sevens_stack, three_stack]).view(-1, 28 * 28)

In [86]:
train_y = tensor([1] * len(threes) + [0] * len(sevens)).unsqueeze(1)

In [87]:
train_x.shape, train_y.shape

(torch.Size([12530, 784]), torch.Size([12396, 1]))

In [93]:
#A dataset is required to return a tuple of x,y when indexed.

dset = list(zip(train_x, train_y))

In [95]:
x,y = dset[0]

In [96]:
x.shape

torch.Size([784])

In [97]:
y

tensor([1])

In [106]:
valid_3_tens = torch.stack([tensor(Image.open(o)) for o  in (threes)])
valid_7_tens = torch.stack([tensor(Image.open(o)) for o in(sevens)])

In [107]:
valid_3_tens = valid_3_tens.float() /255

In [108]:
valid_7_tens = valid_7_tens.float() /255

In [ ]:
valid_x =  torch.cat(valid_3_tens, valid_7_tens).view(-1,28 * 28)

In [ ]:
valid_x = torch.cat(valid_3_tens, valid_7_tens).view(-1, 28 * 28)

In [ ]:
valid_x = torch.cat([valid_3_tens, valid_7_tens]).view(-1,28*28)  