<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/MSPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors are specialised data structures that are very similar to Arrays and matrices. Tensors are optimized to run on GPUs and other hardware accelerates and also automatic differentiation can be done on tensors

In [ ]:
import torch
import numpy as np

Tensors can be initialized in various ways, even through data and the data type is automatically inferred

In [ ]:
data = [[1,2,3,4],[5,6,7,8]] #Lets create a nested list
data_tensor = torch.tensor(data)

In [ ]:
data_tensor.shape #This is a rank 2 tensor of 4 elements in each tensor

torch.Size([2, 4])

In [ ]:
data_tensor[0].shape #We have accessed the first element in our tensor  and checked the size  it has 4 elements 

torch.Size([4])

In [ ]:
#We can initliaze tensors from numpy arrays 
numpy_array = np.array(data)
tensor_numpy = torch.from_numpy(numpy_array)

In [ ]:
tensor_numpy

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
data_tensor_ones = torch.ones_like(data_tensor) #This tensor retains the properties of the tensor i.e the shape = rank and n.o of elements and the , data type i.e float

In [ ]:
data_tensor_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
#Random tensor
data_rand = torch.rand_like(data_tensor,dtype=torch.float)

In [ ]:
data_rand

tensor([[0.1110, 0.8282, 0.0371, 0.0832],
        [0.1303, 0.6182, 0.7145, 0.4051]])

In [ ]:
shape = (2,3,) #This is tuple that defines the shape of the tensor we want to create randomly 
rand_tensor = torch.rand(shape) #The shape we defined is 2,3 which means we want to create a rank 2 tensor of 3 elements each

In [ ]:
rand_tensor

tensor([[0.6455, 0.4153, 0.9425],
        [0.6195, 0.9566, 0.7318]])

The attributes of a tensor describe their shape, dtype and device on which they are stored in 

In [ ]:
data = torch.rand(2,3)

In [ ]:
data.shape

torch.Size([2, 3])

In [ ]:
data.dtype

torch.float32

In [ ]:
data.device

device(type='cpu')

Operations on Tensors :Manipulation, transposing, indexing and slicing

Copying Tensors to cuda

In [ ]:
#Copying a tensor to cuda
if torch.cuda.is_available():
  data.to("cuda")

Standard numpy indexing and slicing 

In [ ]:
#Random tensor of ones
tensor = torch.ones(2,4) #Rank 2 tensor of 4 elements 

In [ ]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
tensor[0][:2] #Slicing  and indexing 

tensor([1., 1.])

In [ ]:
tensor_rand = torch.ones(4,4)

In [ ]:
tensor_rand[:,0]

tensor([1., 1., 1., 1.])

In [ ]:
two_four = torch.ones(2,4)

In [ ]:
two_four

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
two_four[:,0]

tensor([1., 1.])

In [ ]:
two_four[:,-1]

tensor([1., 1.])

Joining tensors

In [ ]:
two_four = torch.ones(4,4)

In [ ]:
tensor_rand = torch.ones(4,4)

In [ ]:
torch.cat([two_four, tensor_rand], dim =1) #Concatenating tensors in the same dimension such 4,4 dimensions can be joined  together
x =torch.stack((two_four, tensor_rand))

Arithmetic operations 

In [ ]:
tensor = torch.rand(2,4)

In [ ]:
tensor.T

tensor([[0.3046, 0.1900],
        [0.6411, 0.4928],
        [0.5276, 0.0154],
        [0.9121, 0.9188]])

In [ ]:
tensor

tensor([[0.3046, 0.6411, 0.5276, 0.9121],
        [0.1900, 0.4928, 0.0154, 0.9188]])

In [ ]:
#We do a matrix multiplication 
y1 = tensor @ tensor.T

In [ ]:
y1

tensor([[1.6140, 1.2199],
        [1.2199, 1.1234]])

In [ ]:
y2 = tensor.matmul(tensor.T)

In [ ]:
y2

tensor([[1.6140, 1.2199],
        [1.2199, 1.1234]])

In [2]:
import torch
import numpy as np


In [6]:
#Creating a tensor automatically from data the data type is automatically inferred in Pytorch
data = list([[1,2],[3,4]])

In [7]:
tensor_data = torch.tensor(data)

In [8]:
tensor_data

tensor([[1, 2],
        [3, 4]])

In [11]:
#Creating tensors from a numpy array 
np_array = np.array(data)
#Torch.from_numpy
numpy_tensor = torch.from_numpy(np_array)

In [14]:
#Pass in the nested list data into a numpy array 
np_array = np.array(data)
np_tensor = torch.from_numpy(np_array)

In [12]:
numpy_tensor

tensor([[1, 2],
        [3, 4]])

In [15]:
np.multiply(np_array,2,out=np_array)

array([[2, 4],
       [6, 8]])

In [16]:
#Creating a tensor from another tensor 
x_one = torch.ones_like(tensor_data)

In [19]:
tensor_data.shape

torch.Size([2, 2])

In [21]:
x_one.shape  #This is a rank two tensor of two elements in each tensor 

torch.Size([2, 2])

In [22]:
#Creating a random tensor
rand_tens = torch.rand(2,4)

In [23]:
rand_tens

tensor([[0.2445, 0.8288, 0.8323, 0.0331],
        [0.8054, 0.6415, 0.9139, 0.1344]])

In [24]:
tensor_data

tensor([[1, 2],
        [3, 4]])

In [26]:
#Lets create a random tensor based on the dimensions of a previous tensor
torch.rand_like(tensor_data, dtype=torch.float) #Here we created a tensor of random values with a different data type

tensor([[0.0199, 0.6999],
        [0.4332, 0.7387]])

In [30]:
#Shape shows the number of rows and columns in a tensor
#We can create tensors of ones zeros and random values
shape = (2,4) #Tuple of 2 and 4 this would be the rows and columns in our tensors 
ones = torch.ones(shape)
zeros = torch.zeros(shape)
rand = torch.rand(shape)

In [34]:
ones#Tensor with ones as elements

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
zeros #Tensor with zeros as elements

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
rand #Random elements in the tensor

tensor([[0.6097, 0.9103, 0.9038, 0.5740],
        [0.3606, 0.2090, 0.1051, 0.1375]])

In [38]:
#Attributes of a tensor describe the shape, dataType and device on which they are stored in
shape = (4,4)
rand_tens = torch.rand(shape, dtype=torch.float64)

In [39]:
rand_tens

tensor([[0.3804, 0.8398, 0.0549, 0.0200],
        [0.9941, 0.3644, 0.2217, 0.9242],
        [0.9877, 0.3287, 0.5147, 0.3859],
        [0.7140, 0.6558, 0.0457, 0.4861]], dtype=torch.float64)

In [42]:
#Lets check the shape of our tensor
rand_tens.shape #Clearly this is a tensor of rank 4 which means is has 4 rows and 4 columns

torch.Size([4, 4])

In [43]:
#Lets check the data type of our tensor
rand_tens.dtype

torch.float64

In [44]:
#Lets check the device on which they are stored
rand_tens.device

device(type='cpu')

In [ ]:
#Arithmetic operations on tensors 
#There are over 100 tensor manipulations , linear algebra and matrix manipulations transposing, inversing and indexing a slicing

In [45]:
#Computing the tensor arithmetic operations on GPUs is much faster compared to computing on CPUs 
#GPUs have up to 1000 cores and do computations in paralles processing while CPUs have 16 cores 
#Computations take place in these cores

In [48]:
randShape = (2,4)
rand = torch.rand(randShape)
rand

tensor([[0.9139, 0.4989, 0.2795, 0.3601],
        [0.7563, 0.3411, 0.3512, 0.4247]])

In [51]:
#To do tensor operations on the GPUs we first have to check for GPU availability 
if torch.cuda.is_available():
   rand = rand.to("cuda") #We copy the tensor to the GPU

In [52]:
#Numpy API slicing and Indexing  
randOnes = torch.ones(4,4)

In [54]:
randOnes #Random tensor of ones as elements

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [55]:
randOnes[0]

tensor([1., 1., 1., 1.])

In [56]:
randOnes[0][:2] 

tensor([1., 1.])

In [58]:
randOnes[0][:-1] #Removed one element from the first row in our tensor

tensor([1., 1., 1.])

In [67]:
#Joining two tensors
t1 = torch.ones(2,4)
t2 = torch.cat([t1,t1,t1,t1], dim=1)
t2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [68]:
t2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [73]:
#Matrix multiplications between tensors
t1
t3 = t1 @ t1.T #Matrix multiplication of tensors

In [72]:
t3

tensor([[4., 4.],
        [4., 4.]])

In [75]:
t1.shape

torch.Size([2, 4])

In [76]:
t3.shape

torch.Size([2, 2])

In [78]:
t4 = t1.matmul(t1.T)

In [79]:
t4

tensor([[4., 4.],
        [4., 4.]])

In [80]:
t3

tensor([[4., 4.],
        [4., 4.]])

In [85]:
y3 = torch.rand_like(t3) #Creates a new tensor of random values  with the same dimensions as the previous tensor

In [83]:
y4  = torch.cat([y3,y3,y3],dim=1)

In [84]:
y4

tensor([[0.5125, 0.7976, 0.5125, 0.7976, 0.5125, 0.7976],
        [0.4712, 0.5146, 0.4712, 0.5146, 0.4712, 0.5146]])

In [92]:
y5 = torch.matmul(y4,y4.T, out=y4)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: An output with one or more elements was resized since it had shape [2, 6], which does not match the required output shape [2, 2].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:23.)
  """Entry point for launching an IPython kernel.


In [93]:
y5

tensor([[1.7975, 1.3039],
        [1.5573, 0.6519]])

In [97]:
#Single element tensors
#Let us aggregate elements in our tensor and convert them into a Python numerical value 
agg = y5.sum()
#Let us convert the one element tensor into a Python numerical value
agg_like = agg.item()
agg_like, type(agg_like)

(5.3105292320251465, float)

In [98]:
#In Place operations 

y5.add_(5)

tensor([[6.7975, 6.3039],
        [6.5573, 5.6519]])

In [99]:
y5

tensor([[6.7975, 6.3039],
        [6.5573, 5.6519]])

In [100]:
#Tensors on cpu and numpy arrays can share their underlying memory locations
t = torch.ones(5)

In [101]:
t

tensor([1., 1., 1., 1., 1.])

In [102]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [104]:
#Converting numpy array to tensor
n = np.ones(5)
n_tensor = torch.from_numpy(n)

In [105]:
n_tensor

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [106]:
n_tensor.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [108]:
n #Changes in the tensor reflect changes in the numpy array

array([2., 2., 2., 2., 2.])