<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/MSPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors are specialised data structures that are very similar to Arrays and matrices. Tensors are optimized to run on GPUs and other hardware accelerates and also automatic differentiation can be done on tensors

In [13]:
import torch
import numpy as np

Tensors can be initialized in various ways, even through data and the data type is automatically inferred

In [3]:
data = [[1,2,3,4],[5,6,7,8]] #Lets create a nested list
data_tensor = torch.tensor(data)

In [8]:
data_tensor.shape #This is a rank 2 tensor of 4 elements in each tensor

torch.Size([2, 4])

In [11]:
data_tensor[0].shape #We have accessed the first element in our tensor  and checked the size  it has 4 elements 

torch.Size([4])

In [15]:
#We can initliaze tensors from numpy arrays 
numpy_array = np.array(data)
tensor_numpy = torch.from_numpy(numpy_array)

In [16]:
tensor_numpy

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [19]:
data_tensor_ones = torch.ones_like(data_tensor) #This tensor retains the properties of the tensor i.e the shape = rank and n.o of elements and the , data type i.e float

In [18]:
data_tensor_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [27]:
#Random tensor
data_rand = torch.rand_like(data_tensor,dtype=torch.float)

In [28]:
data_rand

tensor([[0.0094, 0.6995, 0.9222, 0.2602],
        [0.8899, 0.6198, 0.2974, 0.8269]])

In [30]:
shape = (2,3,) #This is tuple that defines the shape of the tensor we want to create randomly 
rand_tensor = torch.rand(shape) #The shape we defined is 2,3 which means we want to create a rank 2 tensor of 3 elements each

In [31]:
rand_tensor

tensor([[0.7066, 0.0033, 0.3923],
        [0.5645, 0.3294, 0.6664]])

The attributes of a tensor describe their shape, dtype and device on which they are stored in 

In [32]:
data = torch.rand(2,3)

In [37]:
data.shape

torch.Size([2, 3])

In [35]:
data.dtype

torch.float32

In [36]:
data.device

device(type='cpu')

Operations on Tensors