<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/Nature_of_Nifti_Images.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_string= "Neuro-Imaging is hard but a flair"
my_string

'Neuro-Imaging is hard but a flair'

In [2]:
type(my_string)

str

In [3]:
n = len(my_string)#The string has about 33 characters 

In [4]:
#We can print the first character of the string
my_string[0]

'N'

In [5]:
#Last character of the string 
last = my_string[n-1]

In [6]:
last

'r'

In [7]:
#Let's get the first two characters of the string
first_two = my_string[0:2]
first_two

'Ne'

In [8]:
#The first five characters of the string 
five = my_string[0:5]

In [9]:
five

'Neuro'

In [10]:
#Import module for interacting with the operating system
import os
#Get the CWD
cwd = os.getcwd()

In [11]:
print(cwd)
loc = cwd

/content


In [12]:
#with open(os.path.join(str(loc),))
with open("textbook.txt",'w') as f:
  f.write("scripts', 'voxel_time_course.txt', 'model_one_voxel.Rmd', 'map_coordinates.Rmd', 'image_header_and_affine.Rmd', 'bib', 'on_modules.Rmd', 'participate.md', 'git_walk_through.Rmd', 'numpy_squeeze.Rmd', 'images_3d.Rmd', 'bonferroni_correction.Rmd', 'rotation_2d_3d.md', 'array_reductions.Rmd', 'multi_multiply.Rmd', 'validate_against_scipy.Rmd', 'keyword_arguments.Rmd', 'length_one_tuples.Rmd', 'numpy_random.Rmd', 'on_regression.Rmd', 'more_on_jupyter.Rmd', 'numpy_diag.Rmd', 'full_scripting.md', 'whole_image_statistics.Rmd', 'arrays_and_images.Rmd', 'optimizing_space.Rmd', 'the_problem.md', 'brisk_python.Rmd', 'boolean_indexing_nd.Rmd', 'printing_floating.Rmd', 'exercises.md', 'to_code.md', 'participate_grading.md', 'arrays_3d.Rmd', '.pytest_cache', 'sys_path.Rmd', 'convolution_matrices.Rmd', 'the_software.md', 'classes_and_labs.md', 'tr_and_headers.Rmd', 'dot_outer.Rmd', 'packages_namespaces.Rmd', 'data', 'why_mse_correlation.Rmd', 'resampling_with_ndimage.Rmd', 'mymodule.py', '.gitignore', 'nibabel_affines.Rmd', 'module_directories.Rmd', 'anterior_cingulate.md', 'on_loops.Rmd', 'installation_on_mac.md', 'example_module.py', 'github_dummies_homework.md', 'nibabel_apply_affine.Rmd', 'images', 'numpy_logical.Rmd', 'topics.md', 'intro.md', '_config.yml', 'installation_on_linux.md', 'github_pca_homework.md', 'glm_intro.Rmd', 'otsu_threshold.Rmd', 'reading_text.Rmd', 'using_jupyter.Rmd', 'installation.md', 'non_tr_onsets.Rmd', 'what_is_an_image.Rmd', 'comparing_arrays.Rmd', 'rotations.py', 'truthiness.Rmd', 'string_formatting.Rmd', 'pearson_functions.md', 'introducing_python.Rmd', 'diag_inverse.md', 'newaxis.Rmd', 'subplots.Rmd', '_scripts', 'introducing_nipype.Rmd', 'dipy_registration.Rmd', 'numpy_transpose.Rmd', '__pycache__', 'images_and_affines.Rmd', 'mentors.md', 'check_install.py', 'hypothesis_tests.Rmd', 'voxels_by_time.Rmd', 'docstrings.Rmd', 'tuple_unpacking.Rmd', 'subtract_means.Rmd', 'logistics.md', 'path_manipulation.Rmd', 'reshape_and_4d.Rmd', 'bibliography.md', 'slice_timing.Rmd', 'project_grading.md', '.github', 'volmeans.py', 'surviving_computers.md', 'plot_lines.Rmd', 'some_numbers.txt', 'coding_style.md', '_toc.yml', 'code', 'numpy_intro.Rmd', 'multi_model_homework.md', 'build_requirements.txt', 'mydirmod', 'arange.Rmd', '_build', 'matrix_rank.Rmd', 'validating_data.Rmd', 'using_module.Rmd', 'my_script.py', 'floating_in_text.md', 'intro_to_4d.Rmd', 'another_dir', 'test_rdmodule.py', 'list_comprehensions.Rmd', 'dot_and_outer.md', 'projects.md', 'subtract_mean_math.md', 'rdmodule.py', 'simplemod.py', 'reshape_and_3d.Rmd', '_todo.md', 'dunders.Rmd', 'numpy_meshgrid.Rmd', 'string_literals.Rmd', 'assert.Rmd', 'classes.md', 'git_workflow_exercises.md', 'slicing_with_booleans.Rmd', 'glossary.md', 'mean_test_example.Rmd', 'Makefile', 'methods_vs_functions.Rmd', 'on_convolution.Rmd', 'ds114_sub009_t2r1_conv.txt', 'on_correlation.Rmd', 'slope_with_deviations.Rmd', 'another_example.py', 'regress_one_voxel.Rmd', 'choosing_editor.md', 'index_reshape.Rmd', 'installation_on_windows.md', 'syllabus.md', 'voxel_time_courses.Rmd', 'git_videos.md', 'CNAME', 'example_data.md', 'saving_images.Rmd', 'github_glm_homework.md', '.git', 'nans.md', 'convolution_background.Rmd', 'comparing_floats.md', 'test_one_voxel.Rmd', 'boolean_indexing.Rmd', 'requirements.txt', 'diagonal_zooms.Rmd', 'on_testing.Rmd', 'allclose.Rmd', 'dipy_registration.py")

In [13]:
print(os.listdir(cwd))

['.config', 'textbook.txt', 'sample_data']


In [14]:
!pip install nipraxis
import nipraxis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [15]:
structral_file = nipraxis.fetch_file('ds114_sub009_highres.nii')

In [16]:
structral_file

'/root/.cache/nipraxis/0.4/ds114_sub009_highres.nii'

In [17]:
fobj = open(structral_file,'rb') #Python object to read data from the file into memory
print(fobj)

<_io.BufferedReader name='/root/.cache/nipraxis/0.4/ds114_sub009_highres.nii'>


In [18]:
contents= fobj.read()

In [19]:
type(contents)

bytes

In [20]:
len(contents)

40894816

In [21]:
contents[70:70]

b''

In [22]:
contents[:352]

b'\\\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00r\x00\x03\x00\x00\x01\x9c\x00\x00\x01\x01\x00\x01\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00 \x00\x00\x00\x00\x00\x80?\x00\x00\x80?\xafm\xa6?\x00\x00\x80?\xa3@\x1f<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0C\x00\x00\x80?\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00FSL5.0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00}\x96\xf0\xbd:w\x05<X+\xb8<c\

In [23]:
fmt_specifier = "h"

In [24]:
data_type_chars = contents[70:70]

In [25]:
import struct
#datatype = struct.unpack(fmt_specifier, data_type_chars)

In [26]:
import nibabel

In [27]:
print(nibabel.__version__)

3.0.2


In [28]:
#Load the medical image with nibabel and check the type
image = nibabel.load(structral_file)
type(image) #Type is nibabel.nifti1.Nifti1Image

nibabel.nifti1.Nifti1Image

In [29]:
print(image.header) #Contains metadata

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 256 156 256   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.        1.        1.3002223 1.        0.00972   0.        0.
 0.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FSL5.0'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : -0.11747453
quatern_c       : 0.008146102
quatern_d       : 0.022481605
qoffset_x       : -129.82573
qoffset_y 

In [30]:
#Import numpy 
import numpy 
numpy #Numpy library.

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [31]:
numpy.pi # 
import numpy as np
np.pi

3.141592653589793

In [32]:
import nipraxis
#Fetch the file stem 
stim_fname = nipraxis.fetch_file('24719.f3_beh_CHYM.csv')
stim_fname

'/root/.cache/nipraxis/0.4/24719.f3_beh_CHYM.csv'

In [33]:
lines = open(stim_fname, 'rt').readlines()
lines[:5]

['response,response_time,trial_ISI,trial_shape\n',
 'None,0,2000,red_star\n',
 'None,0,1000,red_circle\n',
 'None,0,2500,green_triangle\n',
 'None,0,1500,yellow_square\n']

In [34]:
lines = open(stim_fname,'rt').readlines()
lines[:5]

['response,response_time,trial_ISI,trial_shape\n',
 'None,0,2000,red_star\n',
 'None,0,1000,red_circle\n',
 'None,0,2500,green_triangle\n',
 'None,0,1500,yellow_square\n']

In [35]:
lines[:5]


['response,response_time,trial_ISI,trial_shape\n',
 'None,0,2000,red_star\n',
 'None,0,1000,red_circle\n',
 'None,0,2500,green_triangle\n',
 'None,0,1500,yellow_square\n']

In [36]:
#del lines[0]

In [37]:
lines[:5]

['response,response_time,trial_ISI,trial_shape\n',
 'None,0,2000,red_star\n',
 'None,0,1000,red_circle\n',
 'None,0,2500,green_triangle\n',
 'None,0,1500,yellow_square\n']

In [38]:
n_trials = len(lines)

In [39]:
n_trials

321

In [40]:
#Use the split method to split the string at commas to give us a list of strings
parts = lines[0].split(',')
parts

['response', 'response_time', 'trial_ISI', 'trial_shape\n']

In [41]:
rt_list = [] #Respsonse time list 
isi_list = []#time between intervals list 
#for i in range(n_trials):
 # line = lines[i]
 # parts = line.split(',')
  #rt_list.append(float(parts[1]))
  #isi_list.append(float(parts[2]))

#Show the first trial ISIs
isi_list[:5]

[]

In [42]:
#We need arrays to help us process data
isi_array = np.array(isi_list)
isi_array

array([], dtype=float64)

In [43]:
rt_array = np.array(rt_list)
rt_array

array([], dtype=float64)

In [44]:
rt_array.shape  #Shape of the repsonse time array

(0,)

In [45]:
isi_array

array([], dtype=float64)

In [46]:
isi_array.dtype #We cannot add a value that is not a floating point number 

dtype('float64')

In [47]:
#isi_array[0] = "some text"  #Raises a value  error

In [48]:
#Arrays are different from python lists which allow use of different data types 
py_list = [5,5,'Hi there Pi', 32]
py_list

[5, 5, 'Hi there Pi', 32]

In [49]:
#rt_array = np.zeros(n_trials)
#rt_array

In [50]:
#rt_array = np.zeros(n_trials)

In [51]:
#rt_array

In [56]:
rt_array = np.zeros(n_trials)
isi_array = np.zeros(n_trials)
for i in range(1,n_trials-1):
  line = lines[i]
  part = line.split(',')
  #rt_arry[i] = float(part[1])
  isi_array[i] = float(part[2])

In [57]:
isi_array[:5]

array([   0., 2000., 1000., 2500., 1500.])

In [64]:
exp_onset_times = np.zeros(n_trials)
start_time = 0 
for i in range(0,n_trials-1):
  start_time = start_time + isi_array[i]
  exp_onset_times[i] = start_time

In [65]:
#Show the first ten values
exp_onset_times[:10]

array([    0.,  2000.,  3000.,  5500.,  7000.,  8500., 10500., 13000.,
       14500., 16500.])

In [69]:
#Show the cumulative sum 
#Exponential  onset times
exp_onset_times = np.cumsum(isi_array)
exp_onset_times[:10]

array([    0.,  2000.,  3000.,  5500.,  7000.,  8500., 10500., 13000.,
       14500., 16500.])

In [72]:
scan_onset_times = np.zeros(n_trials)
for i in range(n_trials):
  scan_onset_times[i] =exp_onset_times[i] + 4000
scan_onset_times[:10]

array([ 4000.,  6000.,  7000.,  9500., 11000., 12500., 14500., 17000.,
       18500., 20500.])

In [74]:
#Numpy can easily add a number to every element in an array 
scan_onset_times = exp_onset_times + 4000

In [77]:
scan_onset_times[:10]

array([ 4000.,  6000.,  7000.,  9500., 11000., 12500., 14500., 17000.,
       18500., 20500.])

In [80]:
scan_length_ms = 2000
6000 / scan_length_ms

3.0

In [82]:
#With a single number numpy can divide every element by the number provides 
scan_onset_times = exp_onset_times / 6000
scan_onset_times[:10]

array([0.        , 0.33333333, 0.5       , 0.91666667, 1.16666667,
       1.41666667, 1.75      , 2.16666667, 2.41666667, 2.75      ])

Processing reaction times

In [83]:
rt_array[:15]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
scan_onset_times[:15]

array([0.        , 0.33333333, 0.5       , 0.91666667, 1.16666667,
       1.41666667, 1.75      , 2.16666667, 2.41666667, 2.75      ,
       2.91666667, 3.08333333, 3.33333333, 3.58333333, 3.91666667])

In [91]:
scan_response_times = np.zeros(n_trials)
for i in range(n_trials):
  trial_onset = scan_onset_times[i]
  this_rt = rt_array[i] 
  scan_response_times[i] = trial_onset + this_rt
scan_response_times[i] = trial_onset + this_rt
scan_response_times[:15]

array([0.        , 0.33333333, 0.5       , 0.91666667, 1.16666667,
       1.41666667, 1.75      , 2.16666667, 2.41666667, 2.75      ,
       2.91666667, 3.08333333, 3.33333333, 3.58333333, 3.91666667])

In [94]:
#Numpy can do element wise addition
scan_response_times = scan_onset_times + rt_array
scan_response_times[:15]

array([0.        , 0.33333333, 0.5       , 0.91666667, 1.16666667,
       1.41666667, 1.75      , 2.16666667, 2.41666667, 2.75      ,
       2.91666667, 3.08333333, 3.33333333, 3.58333333, 3.91666667])

Boolean arrays 

In [96]:
#We still have a problem of 0 values indicating no response time 
#We could use boolean arrays to select values that were not equal to zero 
first_rts = rt_array[:15]
first_rts 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [97]:
#Comparisons are operators that give answers to a boolean operation 
first_rts[0] > 0 

False

In [99]:
first_rts > 0 #Here we can see the values where the was no response 

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [101]:
#The above code is the same as 
print(f"Postion 0 :{first_rts[0]>0}")
print(f"Postion 1 :{first_rts[1]>0}")
print(f"Postion 2 :{first_rts[2]>0}")
print(f"Postion 3 :{first_rts[3]>0}")
print(f"Postion 4 :{first_rts[4]>0}")

Postion 0 :False
Postion 1 :False
Postion 2 :False
Postion 3 :False
Postion 4 :False


In [107]:
#We can get the response time array for all reaction times by: 
rts_arry_not_zero = rt_array
rts_arry_not_zero[:50] > 0 

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [111]:
#rt_array[rts_arry_not_zero]

In [141]:
all_times = np.zeros((n_trials,2))
all_times.shape

(321, 2)

In [144]:
all_times[:,0] = isi_array

In [145]:
all_times[:,1] = rt_array

In [146]:
all_times[:5,:] #SHow all the five rows and first five colums

array([[   0.,    0.],
       [2000.,    0.],
       [1000.,    0.],
       [2500.,    0.],
       [1500.,    0.]])

In [147]:
all_times.shape

(321, 2)

In [148]:
new_shape = [n_trials * 2]

In [149]:
new_shape

[642]

In [152]:
#Reshaping the array 
new_array = np.reshape(all_times,n_trials * 2)
#new_array

In [157]:
flatten = np.reshape(all_times,[n_trials * 2])
flatten.shape

(642,)

In [155]:
#The first 10 values 
flatten[:10]

array([   0.,    0., 2000.,    0., 1000.,    0., 2500.,    0., 1500.,
          0.])

In [167]:
unflattened = np.reshape(flatten,[n_trials*2])

In [168]:
unflattened.shape

(642,)

In [171]:
#Show the first five rows
#unflattened[:5,:]

Arrays as images and images as arrays