<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/Reshaping_and_Three_Dimensional_Arrays_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 

In [6]:
array_1d =  np.arange(6)
array_1d 
type(array_1d.dtype)

numpy.dtype[int64]

In [9]:
array_1d.shape 

#Type 
type(array_1d.shape) #Tuple

tuple

In [22]:
#Lists and tuples 
python_list = [1,2,3]
python_tuple = (1,2,3)

In [21]:
#We can get the length and index the tuple just like we can do with the list 
len(python_tuple)
len(python_list)
#Indexing 
print(f"The length of the python list is: {len(python_list)}")
print(f"The length of the python tuple is: {len(python_tuple)}")

#Indexing
print(f"Fetch the first element from the list{python_list[0]}")
print(f"Fetch the first element from the tuple {python_tuple[0]}")

The length of the python list is: 3
The length of the python tuple is: 3
Fetch the first element from the list1
Fetch the first element from the tuple 1


In [25]:
#Python interprets these parenthesis  in arithmetic
just_number = (1)
just_number 

1

In [27]:
#A length one tuple is formed by appending a trailing comma 
length_one = (1,)
length_one

(1,)

In [32]:
#Lets create a 2d Array using tuples 
#Start by creating a 1d array 
array_1d = np.arange(6)
array_1d

#We reshape this 1d array, through a tuple 
new_shape = (2,3)
array_2d =  np.reshape(array_1d, new_shape)
array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
#Another one dimensional array using single character strings 
another_1d_array = np.array(['a','b','c','d','e','f','g','h','i'])

#Reshape this 1d array into a 3 by 3 2d array
new_shape_another = (3,3)
another_2d = np.reshape(another_1d_array, new_shape_another)
another_2d.shape  #We have reshaped a  vector(1D array) into a Matrix(2D array)

(3, 3)

In [48]:
#We can reshape back the 2d arrays to  1d
print(np.prod(another_2d.shape))#Get the total number of elements
new_vector = (9,)
#Reshape  the 2d array back into a vector
np.reshape(another_2d, new_vector) #We have reshaped our 2d array into a vector

9


array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [51]:
np.reshape(array_2d,(-1,))

array([0, 1, 2, 3, 4, 5])

In [52]:
np.reshape(another_2d,(-1,))

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [57]:
#The shortcut method for flattening/ converting a 2d or a 3d array to a 1d array(Vector)
array_new = np.arange(6)
new_shape = (2,3)

#Two Dimensional array
new_2d = np.reshape(array_new,new_shape)
new_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
#Converting back the 2d array into a vector(1d array)
shape_oneD = (6,)

vector_new = np.reshape(new_2d,shape_oneD)
vector_new

#Shortcut to reshape  a 2d or a 3d array into  a one dimensional array, a vector
np.ravel(new_2d)

array([0, 1, 2, 3, 4, 5])

In [64]:
#We can reshape an array to any shape as long as the number of elements stays the same.,

In [74]:
#print(array_2d.shape) #This is a 2,3 array we reshape to 3 by 2

new_shape = (3,2)

reshaped  = np.reshape(new_2d,new_shape)

reshaped.shape
print(f"Size of array before reshaping {new_2d.size}")
print(f"Size of array after reshaping {reshaped.size}")

Size of array before reshaping 6
Size of array after reshaping 6


In [77]:
#Show the 1d array
array_1d

array([0, 1, 2, 3, 4, 5])

In [79]:
np.reshape(array_2d,(3,-1)) #Reshape to an array with 3 columns and whatever number the columns fit in

array([[0, 1],
       [2, 3],
       [4, 5]])

In [81]:
#Reshape to an array  with 2 columns and whatever number the rows in
np.reshape(array_2d,(3,-1))

array([[0, 1],
       [2, 3],
       [4, 5]])