<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/Reshaping_and_Three_Dimensional_Arrays_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
array_1d =  np.arange(6)
array_1d 
type(array_1d.dtype)

numpy.dtype[int64]

In [3]:
array_1d.shape 

#Type 
type(array_1d.shape) #Tuple

tuple

In [4]:
#Lists and tuples 
python_list = [1,2,3]
python_tuple = (1,2,3)

In [5]:
#We can get the length and index the tuple just like we can do with the list 
len(python_tuple)
len(python_list)
#Indexing 
print(f"The length of the python list is: {len(python_list)}")
print(f"The length of the python tuple is: {len(python_tuple)}")

#Indexing
print(f"Fetch the first element from the list{python_list[0]}")
print(f"Fetch the first element from the tuple {python_tuple[0]}")

The length of the python list is: 3
The length of the python tuple is: 3
Fetch the first element from the list1
Fetch the first element from the tuple 1


In [6]:
#Python interprets these parenthesis  in arithmetic
just_number = (1)
just_number 

1

In [7]:
#A length one tuple is formed by appending a trailing comma 
length_one = (1,)
length_one

(1,)

In [8]:
#Lets create a 2d Array using tuples 
#Start by creating a 1d array 
array_1d = np.arange(6)
array_1d

#We reshape this 1d array, through a tuple 
new_shape = (2,3)
array_2d =  np.reshape(array_1d, new_shape)
array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
#Another one dimensional array using single character strings 
another_1d_array = np.array(['a','b','c','d','e','f','g','h','i'])

#Reshape this 1d array into a 3 by 3 2d array
new_shape_another = (3,3)
another_2d = np.reshape(another_1d_array, new_shape_another)
another_2d.shape  #We have reshaped a  vector(1D array) into a Matrix(2D array)

(3, 3)

In [10]:
#We can reshape back the 2d arrays to  1d
print(np.prod(another_2d.shape))#Get the total number of elements
new_vector = (9,)
#Reshape  the 2d array back into a vector
np.reshape(another_2d, new_vector) #We have reshaped our 2d array into a vector

9


array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [11]:
np.reshape(array_2d,(-1,))

array([0, 1, 2, 3, 4, 5])

In [12]:
np.reshape(another_2d,(-1,))

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [13]:
#The shortcut method for flattening/ converting a 2d or a 3d array to a 1d array(Vector)
array_new = np.arange(6)
new_shape = (2,3)

#Two Dimensional array
new_2d = np.reshape(array_new,new_shape)
new_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
#Converting back the 2d array into a vector(1d array)
shape_oneD = (6,)

vector_new = np.reshape(new_2d,shape_oneD)
vector_new

#Shortcut to reshape  a 2d or a 3d array into  a one dimensional array, a vector
np.ravel(new_2d)

array([0, 1, 2, 3, 4, 5])

In [15]:
#We can reshape an array to any shape as long as the number of elements stays the same.,

In [16]:
#print(array_2d.shape) #This is a 2,3 array we reshape to 3 by 2

new_shape = (3,2)

reshaped  = np.reshape(new_2d,new_shape)

reshaped.shape
print(f"Size of array before reshaping {new_2d.size}")
print(f"Size of array after reshaping {reshaped.size}")

Size of array before reshaping 6
Size of array after reshaping 6


In [17]:
#Show the 1d array
array_1d

array([0, 1, 2, 3, 4, 5])

In [18]:
np.reshape(array_2d,(3,-1)) #Reshape to an array with 3 columns and whatever number the columns fit in

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
#Reshape to an array  with 2 columns and whatever number the rows in
np.reshape(array_2d,(3,-1))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
#Creating 3D arrays 
#Numpy starts by creating a one dimensional array 
array_bigger = np.arange(24)
array_bigger
#Check the shape 
array_bigger.shape 

#Reshape to 3D
new_shape  = (2,4,3)
three_dimension = np.reshape(array_bigger,new_shape)
three_dimension.shape #We have reshaped the 1 array  into a 3d array 

(2, 4, 3)

Reshaping a three dimensional array

In [29]:
#Creating a 3D array 
#We start with a 1d array: Vector
array_1d = np.arange(24)
array_1d

#We reshape into a 3d  array 
new_shape  = (2,3,4) #This can be read as two rows, 3 columns and  4 planes

reshaped = np.reshape(array_1d,new_shape)
reshaped

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
#Lets get the first plane
reshaped[:,:,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [32]:
reshaped #Each row has 3 rows and 4 columns 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
print(f"The first row of data from the 3D array:{reshaped[0,:,:]}")

The first row of data from the 3D array:[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
print(f"The second row of data from the 3D array:{reshaped[1,:,:]}")

The second row of data from the 3D array:[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [39]:
#We reshape the array back to 1d 
new_shape = (24,)
array_1d = np.reshape(reshaped,new_shape)
array_1d.shape

(24,)

In [42]:
reshaped
#Reshaping the array back to 1d using the dedicated numpy function 
array_1d = np.ravel(reshaped)
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
#When reshaping to three dimensions numpy fills out the last then the second then the first
array_reshaped = np.reshape(array_1d,(2,3,4))
array_reshaped

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])