<a href="https://colab.research.google.com/github/Reptilefury/coursera-machine-learning/blob/main/Three_Dimensional_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
#Set the gray as default colormap 
plt.rcParams['image.cmap'] = 'gray'

#Display array values to 4 digits of precision
np.set_printoptions(precision = 4,suppress=True)

#First 2d array 
first_1d = np.arange(10,22) #Creates a 2d array  which is a vector
second_2d = np.reshape(first_1d,(4,3)) #Creates a 2d array that has 4 rows and 3 columns

In [9]:
#Lets visulaize the created 2d array 
second_2d

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [11]:
#We can get rows from the 2D arrays 
second_2d[2,:] #Here we get the third row of the 2d array  with all the values in the column

array([16, 17, 18])

In [14]:
second_2d[:,2] #Here we get all the values in the third row of our 2d array

array([12, 15, 18, 21])

In [15]:
second_2d[1,:]

array([13, 14, 15])

In [18]:
#A 2D array, two dimensional array has two dimensions (rows,columns)
second_2d.shape #Our 2d array  has 4 elements in the first dimension and 3 elements in the third dimension
#The total number of elements in our array  are 4 * 3  which is 12 elements in total

(4, 3)

In [24]:
#To get the total number  of elements in an array  we can use the np.prod function 
np.prod(second_2d.shape) #This multiplies the first dimension by the second dimension
#It is similar to:
np.prod((4,3)) #Gives us 12 # same as 4 * 3

12

In [35]:
first_1d = np.arange(10,22) #Create a one dimensional array(Vector)
second_2d = np.reshape(first_1d,(4,3)) #Create a 2d array based on the 1d array we just created
second_2d

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [40]:
#To create a 3D array we must first create an empty array of the right shape
#Make a 3d array 
into_3d = np.zeros((4,3,2))
into_3d.shape  

(4, 3, 2)

The 3d array above can be interpreted as 2 planes each with 4 rows and  3 columns. Planes are also known as channels.

In [42]:
#Check the shape of the 3d array we just created
into_3d.shape

(4, 3, 2)

In [43]:
first_1d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [49]:
first_2d = np.reshape(first_1d,(4,3))
first_2d
#100, 112  

#Create the second  2d array 
second_1d = np.arange(100,112)
second_2d = np.reshape(second_1d,(4,3))
second_2d 

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

Currently the first 3D array only contains zeros  so we make the first 2d array be the first 4 by 3 plane of the 2d array

In [51]:
first_2d

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [52]:
#Set all rows and all columns for plane 0 to be the first 2d array
into_3d[:,:,0] =  first_2d

In [54]:
first_2d #We get all rows and columns of the of the first 2d array to be 
#The first 2d array is attached to the first plane of the of the 3d array(first channel)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [55]:
#We can attach the second 2D array to the second plane of the  of our 3D array
into_3d[:,:,1] = second_2d

In [56]:
second_2d

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [70]:
#Lets create another empty 3D array to the 
threeD = np.zeros((3,4,5))
threeD #We this is an empty 3D array of 4 rows and 5 colums 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [76]:
#Transpose the 3D array we just created
threeD_transpose = threeD.T
threeD_transpose
#The array becomes a 5 dimensional array  of 4 rows and 3 columns in  each plane/channel

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
threeD_transpose.shape

(5, 4, 3)

In [77]:
into_3d

array([[[ 10., 100.],
        [ 11., 101.],
        [ 12., 102.]],

       [[ 13., 103.],
        [ 14., 104.],
        [ 15., 105.]],

       [[ 16., 106.],
        [ 17., 107.],
        [ 18., 108.]],

       [[ 19., 109.],
        [ 20., 110.],
        [ 21., 111.]]])

In [78]:
#Slicing a three Dimension array 
into_3d[0,:,:] #Here we get the first row , all columns and planes

array([[ 10., 100.],
       [ 11., 101.],
       [ 12., 102.]])

In [80]:
into_3d[:,:,0]#All rows and all columns of the first plane

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]])

In [ ]:
into_3d[1,:,:] #second rows, second column all planes

In [82]:
empty3d_array = np.zeros((3,4,5)) #We just created a 3d array of 4 rows and 5 columns

In [84]:
empty3d_array #The array is empty

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [102]:
#To create a 2d array we  create a 1d array  and reshape it to a 2d array 
first_array = np.arange(10,22)
first_array #This is a 1d array (Vector)
#We reshape the vector into 2d 
first_twoD = np.reshape(first_array,(3,4))
first_twoD 
#To create a second two dimensional array we create a one dimensional array (a vector) 
second_array = np.arange(10,22)
second_twoD = np.reshape(second_array,(3,4)) 
second_twoD

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [104]:
#We now attach the 2d arrays we created into the planes of the empty array we created earlier
empty3d_array[:,:,1]  = first_twoD #We broadcast/ attach the first 2D array to the first channel of the 3D array
#We broadcast/attach the second 2D array to the second plane of our 3d array

In [105]:
empty3d_array

array([[[10., 10.,  0.,  0.,  0.],
        [11., 11.,  0.,  0.,  0.],
        [12., 12.,  0.,  0.,  0.],
        [13., 13.,  0.,  0.,  0.]],

       [[14., 14.,  0.,  0.,  0.],
        [15., 15.,  0.,  0.,  0.],
        [16., 16.,  0.,  0.,  0.],
        [17., 17.,  0.,  0.,  0.]],

       [[18., 18.,  0.,  0.,  0.],
        [19., 19.,  0.,  0.,  0.],
        [20., 20.,  0.,  0.,  0.],
        [21., 21.,  0.,  0.,  0.]]])

In [110]:
#We get the first row and columns of all planes 
empty3d_array[0,:,:]

array([[10., 10.,  0.,  0.,  0.],
       [11., 11.,  0.,  0.,  0.],
       [12., 12.,  0.,  0.,  0.],
       [13., 13.,  0.,  0.,  0.]])

In [112]:
#Second row all columns of all planes
empty3d_array[1,:,:] #Second row all columns and all planes 

array([[14., 14.,  0.,  0.,  0.],
       [15., 15.,  0.,  0.,  0.],
       [16., 16.,  0.,  0.,  0.],
       [17., 17.,  0.,  0.,  0.]])

In [113]:
#Third row all columns and all planes
empty3d_array[2,:,:]

array([[18., 18.,  0.,  0.,  0.],
       [19., 19.,  0.,  0.,  0.],
       [20., 20.,  0.,  0.,  0.],
       [21., 21.,  0.,  0.,  0.]])

In [129]:
#We create the first 2D array
new_first = np.arange(10,22) #This is a vector that will be used to create a 2D array
new_first_2d = np.reshape(new_first,(4,3))

#Create a second array 
new_second_array = np.arange(10,22)
new_second_2d = np.reshape(new_second_array,(4,3))

#Create a 3D array
threes_3d = np.zeros((4,3,5))

#We broadcast/pass the elements of the 2D array  into the first plane of the  3D array
threes_3d[:,:,0] = new_first_2d
threes_3d
#We broadcast/pass the elements of the second 2d array into the 2nd plane of the 3d array
threes_3d[:,:,1] = new_first_2d
threes_3d

array([[[10., 10.,  0.,  0.,  0.],
        [11., 11.,  0.,  0.,  0.],
        [12., 12.,  0.,  0.,  0.]],

       [[13., 13.,  0.,  0.,  0.],
        [14., 14.,  0.,  0.,  0.],
        [15., 15.,  0.,  0.,  0.]],

       [[16., 16.,  0.,  0.,  0.],
        [17., 17.,  0.,  0.,  0.],
        [18., 18.,  0.,  0.,  0.]],

       [[19., 19.,  0.,  0.,  0.],
        [20., 20.,  0.,  0.,  0.],
        [21., 21.,  0.,  0.,  0.]]])